services:
  postgres:
    image: postgres:latest@sha256:c5bd032fb659503bf121faf5cea5894dcfece30286a3db59e3c060f3e9f60cb0
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  test:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/code
    environment:
      DJANGO_SETTINGS_MODULE: thelabdb.tests.settings.pg
