services:
  postgres:
    image: postgres:latest@sha256:32ca0af8e77bfb8c6610c488e4691f83f972a3e9e64d3b02facf3ab111ad5500
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  test:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/code
    environment:
      DJANGO_SETTINGS_MODULE: thelabdb.tests.settings.pg
