services:
  postgres:
    image: postgres:latest@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'

  test:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/code
    environment:
      DJANGO_SETTINGS_MODULE: thelabdb.tests.settings.pg
