---
site_name: thelab-db

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight

repo_name: thelab-db
repo_url: https://gitlab.com/thelabnyc/thelab-db/
edit_uri: -/edit/master/docs/

docs_dir: docs/
site_dir: build/mkdocs/

extra_css:
  - styles.css

markdown_extensions:
  - toc:
      permalink: True
  # - extra
  - abbr
  # - attr_list
  - def_list
  # - fenced_code
  - footnotes
  - md_in_html
  # - tables
  - codehilite
  - smarty
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - mkautodoc

use_directory_urls: false

plugins:
  - search
  - awesome-pages
  - pagenav-generator
  - section-index
