# Generated by Django 5.1.6 on 2025-02-19 21:05

from django.db import migrations, models

import thelabdb.fields.pydantic
import thelabdb.tests.testsuniv.models


class Migration(migrations.Migration):
    dependencies = [
        ("testsuniv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attrs",
                    thelabdb.fields.pydantic.PydanticField(
                        model_cls=thelabdb.tests.testsuniv.models.ProductAttributes
                    ),
                ),
            ],
        ),
    ]
