# Generated by Django 5.1.7 on 2025-03-21 16:47

from django.db import migrations, models
import django.db.models.deletion

import thelabdb.tests.testsuniv.models


class Migration(migrations.Migration):
    dependencies = [
        ("testsuniv", "0002_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    thelabdb.tests.testsuniv.models.StoreIDAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "rating",
                    thelabdb.tests.testsuniv.models.RatingField(
                        null=True, verbose_name="Store Rating"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_in_stock",
                    thelabdb.tests.testsuniv.models.ProductQtyField(
                        verbose_name="Qty In Stock"
                    ),
                ),
                (
                    "qty_allocated",
                    thelabdb.tests.testsuniv.models.ProductQtyField(
                        verbose_name="Qty Allocated"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="testsuniv.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="testsuniv.store",
                    ),
                ),
            ],
        ),
    ]
