# Generated by Django 5.1.7 on 2025-03-21 18:21

from django.db import migrations, models

import thelabdb.fields.char


class Migration(migrations.Migration):
    dependencies = [
        ("testsuniv", "0003_store_inventory"),
    ]

    operations = [
        migrations.CreateModel(
            name="NullChar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", thelabdb.fields.char.NullCharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="UppercaseChar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", thelabdb.fields.char.UppercaseCharField(max_length=25)),
            ],
        ),
    ]
